In [87]:
#Creating Dataframes Task 1

import pandas as pd
import numpy as np

In [88]:
# Employee Dataframe

employee_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]
})

employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [89]:
#Seniority Dataframe

seniority_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]
})

seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [90]:
#Project Dataframe

project_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8",
                "Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed",
               "Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
})

project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [91]:
#Dataframes to csv files

employee_df.to_csv("Employee.csv", index=False)
seniority_df.to_csv("Seniority.csv", index=False)
project_df.to_csv("Project.csv", index=False)

In [92]:
#Task 2: Handling Missing Values in Project Cost (Running Average Method)

import pandas as pd  # Import pandas
import numpy as np   # Import numpy

project_df = pd.read_csv("Project.csv")  # Load Project dataset

print(project_df)
print(project_df.isnull().sum())         # Count of null values

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished
ID         0
Project    0
Cost       2
Status     0
dtype: int64

In [100]:
cost_list = project_df["Cost"].tolist()        # Convert Cost column to list

running_sum = 0                                
count = 0                                      

for i in range(len(cost_list)):                # Loop through all cost values
    if pd.isna(cost_list[i]):                  
        cost_list[i] = running_sum / count     # Replace NaN with running average
    else:
        running_sum += cost_list[i]            # Add valid value to running sum
        count += 1                             # Increase valid value count

project_df["Cost"] = cost_list                 # Replace Cost column with updated values

In [101]:
project_df

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [105]:
project_df["Cost"] = project_df["Cost"].astype(int)  #scientific notation to int conversion

In [104]:
project_df

      ID     Project     Cost    Status
0   A001   Project 1  1002000  Finished
1   A002   Project 2  2000000   Ongoing
2   A003   Project 3  4500000  Finished
3   A004   Project 4  5500000   Ongoing
4   A005   Project 5  3250500  Finished
5   A002   Project 6   680000    Failed
6   A005   Project 7   400000  Finished
7   A003   Project 8   350000    Failed
8   A001   Project 9  2061714   Ongoing
9   A003  Project 10   300000  Finished
10  A001  Project 11  2000000    Failed
11  A004  Project 12  1000000   Ongoing
12  A004  Project 13  3000000  Finished
13  A005  Project 14   200000  Finished

In [61]:
project_df.to_csv("Project.csv", index=False)

In [106]:
#Task 3

employee_df = pd.read_csv("Employee.csv")

# Split Name column into First Name and LastName
employee_df[["First Name", "LastName"]] = employee_df["Name"].str.split(" ", expand=True)

# Drop the old Name column
employee_df.drop("Name", axis=1, inplace=True)

print(employee_df)

     ID Gender     City  Age First Name   LastName
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [107]:
employee_df.to_csv("Employee.csv", index=False)  #Saving updates in csv file

In [62]:
# Task 4

import pandas as pd

employee_df = pd.read_csv("Employee.csv")
seniority_df = pd.read_csv("Seniority.csv")
project_df = pd.read_csv("Project.csv")

# Merging Employee and Seniority with ID column
final_df = pd.merge(employee_df, seniority_df, on="ID", how="inner")

# Merging the result with Project on ID column
final_df = pd.merge(final_df, project_df, on="ID", how="inner")

In [63]:
final_df

,ID,Gender,City,Age,First Name,LastName,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1002000,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2061714,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2000000,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,680000,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,350000,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000,Finished

In [108]:
final_df.to_csv("Final.csv", index=False)  # Saving updates in csv file

In [109]:
# Task 5

import numpy as np

final_df["Bonus"] = np.where(final_df["Status"] == "Finished", final_df["Cost"] * 0.05, 0)  # Assign 5% of Cost as Bonus

In [110]:
final_df["Bonus"] = final_df["Bonus"].astype(int)  # Convert Bonus values to integer
print(final_df)

      ID     City  Age  First Name   LastName  Designation Level     Project  \
0   A001    Paris   25    Mr. John      Alter                  2   Project 1
1   A001    Paris   25    Mr. John      Alter                  2   Project 9
2   A001    Paris   25    Mr. John      Alter                  1  Project 11
3   A002   London   27  Mrs. Alice  Luxumberg                  2   Project 2
4   A002   London   27  Mrs. Alice  Luxumberg                  1   Project 6
5   A003   Berlin   29     Mr. Tom  Sabestine                  3   Project 3
6   A003   Berlin   29     Mr. Tom  Sabestine                  2   Project 8
7   A003   Berlin   29     Mr. Tom  Sabestine                  3  Project 10
8   A004  Newyork   31   Mrs. Nina      Adgra                  3   Project 4
9   A004  Newyork   31   Mrs. Nina      Adgra                  3  Project 12
10  A004  Newyork   31   Mrs. Nina      Adgra                  3  Project 13
11  A005   Madrid   30    Mrs. Amy      Johny                  4   Project 5
12  A005   Madrid   30    Mrs. Amy      Johny                  4   Project 7
13  A005   Madrid   30    Mrs. Amy      Johny                  4  Project 14

       Cost    Status   Bonus
0   1002000  Finished   50100
1   2061714   Ongoing       0
2   2000000    Failed       0
3   2000000   Ongoing       0
4    680000    Failed       0
5   4500000  Finished  225000
6    350000    Failed       0
7    300000  Finished   15000
8   5500000   Ongoing       0
9   1000000   Ongoing       0
10  3000000  Finished  150000
11  3250500  Finished  162525
12   400000  Finished   20000
13   200000  Finished   10000

In [111]:
final_df.to_csv("Final.csv", index=False)  #Saving updates in csv file

In [112]:
# Task 6

final_df.loc[final_df["Status"] == "Failed", "Designation Level"] -= 1  # Reduce designation level by 1

In [73]:
final_df

,ID,Gender,City,Age,First Name,LastName,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1002000,Finished,50100
1,A001,M,Paris,25,John,Alter,2,Project 9,2061714,Ongoing,0
2,A001,M,Paris,25,John,Alter,1,Project 11,2000000,Failed,0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000,Ongoing,0
4,A002,F,London,27,Alice,Luxumberg,1,Project 6,680000,Failed,0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000,Finished,225000
6,A003,M,Berlin,29,Tom,Sabestine,2,Project 8,350000,Failed,0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000,Finished,15000
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000,Ongoing,0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000,Ongoing,0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000,Finished,150000
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500,Finished,162525
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000,Finished,20000
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000,Finished,10000

In [113]:
final_df = final_df[final_df["Designation Level"] <= 4]  # Remove employees with Des Level greater than 4

In [75]:
final_df

,ID,Gender,City,Age,First Name,LastName,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1002000,Finished,50100
1,A001,M,Paris,25,John,Alter,2,Project 9,2061714,Ongoing,0
2,A001,M,Paris,25,John,Alter,1,Project 11,2000000,Failed,0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000,Ongoing,0
4,A002,F,London,27,Alice,Luxumberg,1,Project 6,680000,Failed,0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000,Finished,225000
6,A003,M,Berlin,29,Tom,Sabestine,2,Project 8,350000,Failed,0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000,Finished,15000
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000,Ongoing,0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000,Ongoing,0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000,Finished,150000
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500,Finished,162525
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000,Finished,20000
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000,Finished,10000

In [114]:
final_df.to_csv("Final.csv", index=False) #Saving updates in csv file

In [77]:
# Task 7

import numpy as np

# Add Mr. / Mrs. based on Gender
final_df["First Name"] = np.where(final_df["Gender"] == "M", "Mr. " + final_df["First Name"],"Mrs. " + final_df["First Name"])

# Drop Gender column
final_df.drop("Gender", axis=1, inplace=True)
print(final_df)

      ID     City  Age  First Name   LastName  Designation Level     Project  \
0   A001    Paris   25    Mr. John      Alter                  2   Project 1
1   A001    Paris   25    Mr. John      Alter                  2   Project 9
2   A001    Paris   25    Mr. John      Alter                  1  Project 11
3   A002   London   27  Mrs. Alice  Luxumberg                  2   Project 2
4   A002   London   27  Mrs. Alice  Luxumberg                  1   Project 6
5   A003   Berlin   29     Mr. Tom  Sabestine                  3   Project 3
6   A003   Berlin   29     Mr. Tom  Sabestine                  2   Project 8
7   A003   Berlin   29     Mr. Tom  Sabestine                  3  Project 10
8   A004  Newyork   31   Mrs. Nina      Adgra                  2   Project 4
9   A004  Newyork   31   Mrs. Nina      Adgra                  2  Project 12
10  A004  Newyork   31   Mrs. Nina      Adgra                  2  Project 13
11  A005   Madrid   30    Mrs. Amy      Johny                  3   Project 5
12  A005   Madrid   30    Mrs. Amy      Johny                  3   Project 7
13  A005   Madrid   30    Mrs. Amy      Johny                  3  Project 14

       Cost    Status   Bonus
0   1002000  Finished   50100
1   2061714   Ongoing       0
2   2000000    Failed       0
3   2000000   Ongoing       0
4    680000    Failed       0
5   4500000  Finished  225000
6    350000    Failed       0
7    300000  Finished   15000
8   5500000   Ongoing       0
9   1000000   Ongoing       0
10  3000000  Finished  150000
11  3250500  Finished  162525
12   400000  Finished   20000
13   200000  Finished   10000

In [115]:
# Task 8

for i in range(len(final_df)):                     # Loop through each row
    if final_df.loc[i, "Age"] > 29:                # Check if employee age is greater than 29
        final_df.loc[i, "Designation Level"] += 1  # Increase designation by 1

In [80]:
final_df

,ID,City,Age,First Name,LastName,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1002000,Finished,50100
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2061714,Ongoing,0
2,A001,Paris,25,Mr. John,Alter,1,Project 11,2000000,Failed,0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000,Ongoing,0
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,680000,Failed,0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4500000,Finished,225000
6,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 8,350000,Failed,0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,300000,Finished,15000
8,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 4,5500000,Ongoing,0
9,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 12,1000000,Ongoing,0
10,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 13,3000000,Finished,150000
11,A005,Madrid,30,Mrs. Amy,Johny,4,Project 5,3250500,Finished,162525
12,A005,Madrid,30,Mrs. Amy,Johny,4,Project 7,400000,Finished,20000
13,A005,Madrid,30,Mrs. Amy,Johny,4,Project 14,200000,Finished,10000

In [116]:
# Task 9

TotalProjCost = final_df.groupby(["ID", "First Name"])["Cost"].sum().reset_index() # Group by ID / First Name and calculate sum of Cost per employee

TotalProjCost.rename(columns={"Cost": "Total cost"}, inplace=True)                 # Rename to Total cost
print(TotalProjCost)

     ID  First Name  Total cost
0  A001    Mr. John     5063714
1  A002  Mrs. Alice     2680000
2  A003     Mr. Tom     5150000
3  A004   Mrs. Nina     9500000
4  A005    Mrs. Amy     3850500

In [117]:
TotalProjCost.to_csv("TotalProjCost.csv", index=False)   #Saving updates in csv file

In [118]:
# Task 10

result = final_df[final_df["City"].str.contains("o", case=False, na=False)]  # Filter with City column containing letter 'o'

print(result)

      ID     City  Age  First Name   LastName  Designation Level     Project  \
3   A002   London   27  Mrs. Alice  Luxumberg                  2   Project 2
4   A002   London   27  Mrs. Alice  Luxumberg                  0   Project 6
8   A004  Newyork   31   Mrs. Nina      Adgra                  4   Project 4
9   A004  Newyork   31   Mrs. Nina      Adgra                  4  Project 12
10  A004  Newyork   31   Mrs. Nina      Adgra                  4  Project 13

       Cost    Status   Bonus
3   2000000   Ongoing       0
4    680000    Failed       0
8   5500000   Ongoing       0
9   1000000   Ongoing       0
10  3000000  Finished  150000